# TEMPLATE KEY NAME
GL_TEMPLATE_KEY_CONFIGS_NAME = 'configs'
GL_TEMPLATE_KEY_DATUM_NAME = 'datum'
GL_TEMPLATE_KEY_FORMULAS_NAME = 'formulas'
GL_TEMPLATE_KEY_MAPS_NAME = 'maps'
# YAML KEY NAME
GL_CONFIG_YAML_KEY_TEMPLATE_DIR = 'template_dir'
GL_CONFIG_YAML_KEY_DATA_DIR = 'data_dir'
GL_CONFIG_YAML_KEY_OUT_DIR = 'out_dir'
GL_CONFIG_YAML_KEY_TEMPLATE_FILE_NAME = 'template_file_name'
# EXCEL HEADER NAME
GL_EXCEL_HEADER_FILE_NAME = 'FileName'
GL_EXCEL_HEADER_SHEET_NAME = 'SheetName'
GL_EXCEL_HEADER_INSERT_BEFORE_ROW = 'InserBeforeRow'
GL_EXCEL_HEADER_CONFIG_ID = 'ConfigID'
GL_EXCEL_HEADER_To = 'To'
GL_EXCEL_HEADER_FROM = 'From'
# EXCEL SHEET NAME
GL_EXECEL_SHEET_CONFIG_NAME = 'Config'
GL_EXECEL_SHEET_DATA_NAME = 'Data'
GL_EXECEL_SHEET_MAP_NAME = 'Map'
GL_EXECEL_SHEET_FORMULA_NAME = 'Formula'
